### ISSUE TITLE
Umbrella Issue: Server side support for Persisted Queries

### ISSUE THREAD

**Issue by rricard** [apollographql/graphql-server#253]
Effort to implement the server side of https://github.com/apollostack/apollo-client/issues/478.

### Reach a design decision

- [ ] Propose target designs in this issue's thread. We'll mainly try to follow Facebook's reference design expressed in https://github.com/graphql/express-graphql/pull/109 that is likely to end up in the draft.

### Implement persistence management

- [ ] Add a `POST /persist` endpoint that validates and stores the document under a defined hash
- [ ] Add configurable/pluggable query documents storage
- [ ] Create a reference document storage in-memory (for development/experimentation)
- [ ] Create a document storage with Redis in an external package (for production)

### Add persisted document handling to the main `POST /graphql` endpoint

- [ ] Make the endpoint able to receive and match queries from the persisted document store. The query will be executed without validation
– [ ] Add an option to configure the system so it only accepts persisted queries (production).

**Comment by helfer** [comment]
Maybe @Poincare can tune in here? It seems like this is mostly done as far as I can tell!

**Comment by Poincare** [comment]
This thing is done - see [blog post here](https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5#.uo4upqcs3). Maybe we can build better support for it within `graphql-server`.

**Comment by p4bloch** [comment]
@Poincare what do you think about updating the link on that blog post to [apollographql/persistgraphql](https://github.com/apollographql/persistgraphql) instead of the one under your nickname? I had trouble finding it within the apollographql org, and it seems to be the proper one. Thanks!

**Comment by Poincare** [comment]
@p4bloch Thanks for pointing this out - I will get this done :)
